version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "${MYSQL_PATH_DATA}:/var/lib/mysql:rw"
    networks:
      - local
  website:
    image: 'php:8.0-apache'
    container_name: php8-apache
    restart: always
    ports:
      - '80:80'
    networks:
      - local
    build:
      context: ./
      dockerfile: dockerfile
    volumes:
      - "${PROJECT_PATH}:/var/www/html/"
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - "${PROJECT_PATH}:/data"
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

networks:
  local:
    driver: bridge
